/**
 * The only thing that runs inside the customer's CRM.
 *
 * `docs/07` §6 constrains this file more than any other in the product:
 *
 * - **It reads. It does not paint.** The UI is a Side Panel, which lives
 *   outside the page and therefore cannot break the host CRM's layout or
 *   collide with its styles. An injected floating panel works until the CRM
 *   ships a release, and then it is our bug in their product.
 * - **It stores nothing.** The record identifier goes to the service worker
 *   and is never persisted here. A compromised extension must not be able
 *   to leak the lead database, so the lead database is not here to leak.
 * - **The selectors come from the server**, versioned. Salesforce changes
 *   its DOM without warning; a selector shipped inside the extension means
 *   a Chrome Web Store review — days — while the product is broken for
 *   every customer at once.
 *
 * The cascade itself is imported from `shared/crm`, generated by
 * `build.mjs`. A hand-written copy here would drift from the 26 tests that
 * cover it, and the drift would be invisible.
 */

import { detect, mayAutoWrite } from "../vendor/binding.js";
import { writeThroughForm } from "../vendor/overlay.js";

/** The `PageView` the cascade expects, backed by the real document. */
const page = {
  get url() {
    return location.href;
  },
  attribute(selector, name) {
    return document.querySelector(selector)?.getAttribute(name) ?? null;
  },
  read(selector, from) {
    const el = document.querySelector(selector);
    if (!el) return null;
    return from === "value" ? (el.value ?? null) : (el.textContent?.trim() ?? null);
  },
};

/** The `FormWriter`, and the reason L1 writeback is not one line. */
const writer = {
  isEditable(selector) {
    const el = document.querySelector(selector);
    if (!el) throw new Error("no such element");
    return !el.disabled && !el.readOnly;
  },
  fill(selector, value) {
    const el = document.querySelector(selector);
    if (!el) throw new Error("no such element");
    // React and Angular track their own state and ignore a plain assignment
    // to .value. Without the native setter plus an input event, the field
    // *looks* filled, the framework's state stays empty, the agent presses
    // save, and nothing is saved. This is the single most common L1 failure,
    // and `overlay.ts` refuses to believe the write until it reads it back.
    const proto = el instanceof HTMLTextAreaElement
      ? HTMLTextAreaElement.prototype
      : HTMLInputElement.prototype;
    const setter = Object.getOwnPropertyDescriptor(proto, "value")?.set;
    if (setter) setter.call(el, value);
    else el.value = value;
    el.dispatchEvent(new Event("input", { bubbles: true }));
    el.dispatchEvent(new Event("change", { bubbles: true }));
  },
  read(selector) {
    const el = document.querySelector(selector);
    return el ? (el.value ?? el.textContent ?? null) : null;
  },
};

let config = { provider: "unknown", version: 0, rules: [] };
let lastKey = "";

function report() {
  const decision = detect(page, config);
  // The panel is re-rendered on every mutation; only a *change* is worth a
  // message. Chatty extensions are how a CRM tab starts dropping frames.
  const key = JSON.stringify(decision);
  if (key === lastKey) return;
  lastKey = key;
  chrome.runtime.sendMessage({
    type: "binding",
    decision,
    canWrite: mayAutoWrite(decision),
  });
}

chrome.runtime.onMessage.addListener((msg, _sender, respond) => {
  if (msg.type === "config") {
    config = msg.config;
    lastKey = "";
    report();
    return;
  }
  if (msg.type === "writeback") {
    // Verified per field. Only "written" counts as success — see overlay.ts.
    respond(writeThroughForm(writer, msg.fields));
    return true;
  }
});

// A single-page CRM never reloads, so navigation is a DOM mutation.
new MutationObserver(() => report()).observe(document, {
  subtree: true,
  childList: true,
});
addEventListener("popstate", report);
report();
